version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Aa12345678  # Change this to a secure password for production
    command: mongod --bind_ip 0.0.0.0
    networks:
      - app-network

  express-app:
    build:
      context: ../
      dockerfile: ./mydocker03/Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:Aa12345678@mongodb:27017/mydb01?authSource=admin  # Update with your database name
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: